ec2_region: us-east-1
instances_keypair: keypair-name
image_id: ami-bf5021d6
vpc_subnet_id: subnet-29e63245

ec2_instances:
  - instance_type: m1.small
    image: "{{ image_id }}"
    keypair: "{{instances_keypair}}"
    instance_tags:
        Name: web
    exact_tag: 1
    count_tag: 
        Name: web
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    region: "{{ ec2_region }}"

